# Generated by Django 3.2.4 on 2021-07-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("published_date", models.CharField(blank=True, max_length=30)),
                ("average_rating", models.IntegerField(null=True)),
                ("ratings_count", models.IntegerField(null=True)),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("authors", models.ManyToManyField(to="api.Author")),
                ("categories", models.ManyToManyField(blank=True, to="api.Categories")),
            ],
        ),
    ]
