# Generated by Django 3.2.4 on 2021-07-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="average_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="ratings_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
